### PR TITLE
Update peerDependencies to support Grunt 1.0

### PR DESCRIPTION
**Pull request by grunt-updater2**
Update peerDependencies to support Grunt 1.0

Hello,

This is an automated issue request to update the `peerDependencies` for your Grunt plugin.
We ask you to merge this and **publish a new release on npm** to get your plugin working in Grunt 1.0!

Read more here: http://gruntjs.com/blog/2016-02-11-grunt-1.0.0-rc1-released#peer-dependencies
Also on Twitter: https://twitter.com/gruntjs/status/700819604155707392

If you have any questions or you no longer have time to maintain this plugin, then please let us know in this thread.

Thanks for creating and working on this plugin!

(P.S. Close this PR if it is a mistake, sorry)

### CODE REVIEW

**Comment by stefanjudis** [comment]
Hmm... @paazmaya do you have an idea why this is failing now? Unfortunately I don't have the time to look into it right now? :(

**Comment by paazmaya** [comment]
@stefanjudis I will have a look, today.

**Comment by paazmaya** [comment]
Seems to be due to JSON structure https://github.com/danielstjules/jsinspect#json

The tests assumes that the root array has three items, while in fact there is just one, and that one object then has three keys.

**Comment by stefanjudis** [comment]
@danielstjules  

Did we have a breaking change in jsinspect? 
Our tests pass with 0.7.0 and fail with 0.8.0...

**Comment by danielstjules** [comment]
For some reason I can't see the travis build. I can check things out locally later to see what's up. But this is the major difference in output (which isn't a breaking change): https://github.com/danielstjules/jsinspect/commit/358629ae7831848617ce4a51b5eb0ad97484ccf9 Duplications now have an id property.

**Comment by danielstjules** [comment]
My guess is that the resulting duplications are different since bumping to a newer version of acorn and the updates to support ES6

**Pull request merged**
