### PR TITLE
Gruntjs updater peer dep

### PR DESCRIPTION
**Pull request by paazmaya**
Regarding #38

### CODE REVIEW

**Comment by paazmaya** [comment]
@stefanjudis any comments?

**Comment by stefanjudis** [comment]
Uuups... Sorry missed that. Yeah sure. Looks fine for me. :)

Merge and Release tomorrow?

**Comment by paazmaya** [comment]
Your call :rose:

**Comment by stefanjudis** [comment]
@paazmaya You can't release can you? We should change that if you can't. :)

**Comment by stefanjudis** [comment]
I added it you officially on npm... So maybe wanna push it out yourself? :tada:

**Comment by paazmaya** [comment]
I shall try :peach: and publish

**Pull request merged**
